---
- name: Install metric beat
  hosts: webservers
  become: yes
  tasks:

  - name: Download metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

  - name: Install metricbeat
    command: dpkg -i metricbeat-7.4.0-amd64.deb

  - name: drop in metricbeat config
    copy:
      src: /etc/ansible/roles/metric-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable and configure docker module for metric beat
    command: metricbeat modules enable system

  - name: setup metric beat
    command: metricbeat -e setup

  - name: start metric beat
    command: service metricbeat start

  - name: Enable service metrticbeat on boot
    systemd:
      name: metricbeat
      enabled: yes
